use_frameworks!

platform :ios, '10.3'

target 'PrivateUtils_Example' do
  pod 'PrivateUtils', :path => '../'
  pod 'Alamofire'

  target 'PrivateUtils_Tests' do
    inherit! :search_paths

  end
end
